name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: ["Defaults-macOS", "Defaults-iOS", Defaults-tvOS]
        destination:
          [
            "macOS",
            "iOS Simulator,name=iPhone 8",
            "tvOS Simulator,name=Apple TV",
          ]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: xcodebuild clean test -project Defaults.xcodeproj -scheme ${{ matrix.scheme }} -destination "platform=${{ matrix.destination }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.2.1
